In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Data/Customer Churn.csv')
df.head()

Call  Failure  Complains  Subscription  Length  Charge  Amount  \
0              8          0                    38               0   
1              0          0                    39               0   
2             10          0                    37               0   
3             10          0                    38               0   
4              3          0                    38               0   

   Seconds of Use  Frequency of use  Frequency of SMS  \
0            4370                71                 5   
1             318                 5                 7   
2            2453                60               359   
3            4198                66                 1   
4            2393                58                 2   

   Distinct Called Numbers  Age Group  Tariff Plan  Status  Age  \
0                       17          3            1       1   30   
1                        4          2            1       2   25   
2                       24          3            1       1   30   
3                       35          1            1       1   15   
4                       33          1            1       1   15   

   Customer Value  Churn  
0         197.640      0  
1          46.035      0  
2        1536.520      0  
3         240.020      0  
4         145.805      0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3150 entries, 0 to 3149
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Call  Failure            3150 non-null   int64  
 1   Complains                3150 non-null   int64  
 2   Subscription  Length     3150 non-null   int64  
 3   Charge  Amount           3150 non-null   int64  
 4   Seconds of Use           3150 non-null   int64  
 5   Frequency of use         3150 non-null   int64  
 6   Frequency of SMS         3150 non-null   int64  
 7   Distinct Called Numbers  3150 non-null   int64  
 8   Age Group                3150 non-null   int64  
 9   Tariff Plan              3150 non-null   int64  
 10  Status                   3150 non-null   int64  
 11  Age                      3150 non-null   int64  
 12  Customer Value           3150 non-null   float64
 13  Churn                    3150 non-null   int64  
dtypes: float64(1), int64(13)

In [4]:
# Separating attributes
X = df[df.columns[:13]]
# Separating label
y = df['Churn']

In [5]:
from sklearn.preprocessing import StandardScaler
# Call StandardScaler
scaler = StandardScaler()
# Standardization of dataset values
scaler.fit(X)
X = scaler.transform(X)
print(X)

[[ 0.05122913 -0.2878304   0.63672633 ... -0.57466206 -0.11307444
  -0.52875851]
 [-1.05028466 -0.2878304   0.75338358 ...  1.74015315 -0.67934551
  -0.82203616]
 [ 0.32660758 -0.2878304   0.52006909 ... -0.57466206 -0.11307444
   2.0612852 ]
 ...
 [ 0.73967525 -0.2878304  -1.6964185  ... -0.57466206 -0.11307444
  -0.36881527]
 [-0.08646009 -0.2878304  -2.51301919 ... -0.57466206 -0.11307444
   1.17358857]
 [ 0.05122913  3.47426818 -2.51301919 ... -0.57466206 -0.11307444
  -0.71632621]]


In [6]:
# Import train_test_split
from sklearn.model_selection import train_test_split
# Separate training data and test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [7]:
# Import SVM classifier
from sklearn.svm import SVC
# Create SVC object and call fit function to train model
clf = SVC()
clf.fit(X_train, y_train)

SVC()

In [8]:
# Show accuracy score
clf.score(X_test, y_test)

0.9086538461538461

## Another Case

In [9]:
# Mengimpor library
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [10]:
# Mengimpor dataset
dataset = pd.read_csv('Data/Customer Churn.csv')
X = dataset.iloc[:, [2, 3]].values
y = dataset.iloc[:, 4].values

In [11]:
# Menjadi dataset ke dalam Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [12]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
# Membuat model SVM terhadap Training set
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(random_state=0)

In [14]:
# Memprediksi hasil test set
y_pred = classifier.predict(X_test)

In [15]:
# Membuat confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [16]:
print(cm)

[[43  0  0 ...  0  0  0]
 [ 1  0  0 ...  0  0  0]
 [ 1  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  1  0  0]]
